flags:
  time-locale-compat:
    old-locale: false
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- MissingH-1.4.0.1
- aeson-1.2.3.0
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.8
- ansi-wl-pprint-0.6.8.2
- attoparsec-0.13.2.2
- base-compat-0.9.3
- call-stack-0.1.0
- case-insensitive-1.2.0.10
- colour-2.3.4
- directory-tree-0.12.1
- dlist-0.8.0.3
- either-unwrap-1.1
- exceptions-0.10.0
- extensible-exceptions-0.1.1.4
- hashable-1.2.6.1
- haskell-lexer-1.0.1
- hostname-1.0
- hslogger-1.2.10
- indentation-core-0.0.0.1
- indentation-parsec-0.0.0.1
- integer-logarithms-1.0.2
- megaparsec-6.4.0
- mtl-2.2.1
- network-2.6.3.4
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- parser-combinators-0.4.0
- pretty-simple-2.0.2.0
- primitive-0.6.2.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- scientific-0.3.5.2
- split-0.2.3.2
- stm-2.4.5.0
- tagged-0.8.5
- temporary-1.2.1.1
- test-framework-0.8.2.0
- test-framework-hunit-0.3.0.2
- text-1.2.3.0
- text-format-simple-1.1.0
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- uuid-types-1.0.3
- vector-0.12.0.1
- xml-1.3.14
resolver: ghc-8.0.1
