module Main where

import Compiler
import JavaCompiler


main :: IO ()
main = do
    let inputDir = "cobalt_src/"
    let javaOutputDir = "cobalt_generated_java/"
    let classOutputDir = "cobalt_generated_classes/"
    let javaClasspath = ""

    putStrLn "Compiling - Cobalt -> Java"
    putStrLn ""
    compileDir inputDir javaOutputDir
    putStrLn "Complete."

    putStrLn "Compiling - Java -> Byte code"
    compileJavaDir javaClasspath javaOutputDir classOutputDir

    putStrLn "Complete."

    putStrLn "Executing generated Byte code"

    putStrLn "Unimplemented."



