package compiler.tokenizer

object TokenType extends Enumeration {
  type TokenType = Value
  val EMPTY,
  TOKEN,
  IDENTIFIER,
  INTEGER_LITERAL,
  DOUBLE_LITERAL,
  STRING_LITERAL,
  ADD_OPERATOR,
  SUBTRACT_OPERATOR,
  MULTIPLY_OPERATOR,
  DIVIDE_OPERATOR,
  END_STATEMENT,
  COLON,
  SMALLER_THAN,
  SMALLER_THAN_EQUAL,
  LARGER_THAN,
  LARGER_THAN_EQUAL,
  EQUAL_TO = Value
}